version: '3.8'
# build web-frontend container
services:
  web-frontend-dev:
    container_name: web-frontend-${ENV}
    restart: always
    env_file:
      - .env
    environment:
      - PHP_FPM_CLEAR_ENV=no
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
    build: 
      context: .
      dockerfile: Dockerfile-web-frontend
    ports:
      - "80:80"

# build mysql container
  mysql-db:
    container_name: mysql-db-${ENV}
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env

# build mongodb container
  mongodb:
    container_name: mongodb-${ENV}
    image: mongo:4.2
    ports:
      - '27017:27017'
    restart: always
    env_file:
      - .env
