FROM --platform=linux/amd64 php:7.0-apache

# open port for incoming connections
EXPOSE 80

# Update Debian repositories
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/stretch-updates/d' /etc/apt/sources.list \
    && apt-get update \
    && apt-get clean \
    # install db client connectors
    && pecl install mongodb mysql && docker-php-ext-install mysqli \
    # enable php extensions
    && docker-php-ext-enable mysqli

# copy PHP script
COPY ./index.php /var/www/html/

# run Аpache in the background
CMD ["apachectl", "-D", "FOREGROUND"]
